//This is the Main tester for this assignment.
// Credits to the TAs(Josh, Sadie, Honjar) who improved my tester
// If your code passes these test, then you can assume that you have achieved at least 90% of your grade.
public class LinkedListTester {
    public static void main(String[] args) {
        DoublyLinkedList<String> testList = new DoublyLinkedList<String>();
        testList.insertItemAtEnd("C");
        testList.insertItemAtEnd("O");
        testList.insertItemAtEnd("M");
        testList.insertItemAtEnd("P");
        testList.insertItemAtEnd("U");
        testList.insertItemAtEnd("T");
        testList.insertItemAtEnd("E");
        System.out.println("Testing the methods on doubly linked lists with 2 or greater elements:");
        System.out.println("Testing method to print list contents:");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Adding M at beginning of list");
        testList.insertItemAtStart("M");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Adding R at end of list");
        testList.insertItemAtEnd("R");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Removing first element");
        testList.removeStart();
        testList.printList();
        System.out.println("-------------");
        System.out.println("Removing last element");
        testList.removeEnd();
        testList.printList();
        System.out.println("-------------");
        System.out.println("Inserting M before the P");
        testList.insertBefore("P", "M");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Inserting H before the M");
        testList.insertBefore("M", "H");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Inserting B before the A");
        testList.insertBefore("A", "B");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Inserting C after the P");
        testList.insertAfter("P", "C");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Inserting L after the M");
        testList.insertAfter("M", "L");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Removing the M");
        testList.remove("M");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Removing the G");
        testList.remove("G");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Moving P to front");
        testList.moveToFront("P");
        testList.printList();
        System.out.println("-------------");
        System.out.println("Moving L to end");
        testList.moveToEnd("L");
        testList.printList();
        System.out.println("-------------");
// this testing is to check for weird errors which happen when the list is short
// and thus first=last or both are null
        DoublyLinkedList<String> emptyList = new DoublyLinkedList<String>();
        System.out.println("Testing the methods on doubly linked lists with 0 and 1 elements");
        System.out.println("Printing empty list:");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Adding element to start of empty list twice");
        emptyList.insertItemAtStart("A");
        emptyList.insertItemAtStart("B");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Removing elements from start of list 3 times");
        emptyList.removeStart();
        emptyList.removeStart();
        emptyList.removeStart();
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Adding element to end of empty list twice");
        emptyList.insertItemAtEnd("A");
        emptyList.insertItemAtEnd("B");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Removing elements from end of list 3 times");
        emptyList.removeEnd();
        emptyList.removeEnd();
        emptyList.removeEnd();
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Insert before node which doesn't exist twice (should be YZZ)");
        emptyList.insertBefore("A", "Z");
        emptyList.insertBefore("A", "Z");
        emptyList.insertBefore("Z", "Y");
        emptyList.printList();
        System.out.println("-------------");
// clearing list
        System.out.println("Clearing list");
        emptyList.remove("Z");
        emptyList.remove("Z");
        emptyList.remove("Y");
        System.out.println("-------------");
        System.out.println("Insert after node which doesn't exist twice (should be ZAZ)");
        emptyList.insertAfter("Q", "Z");
        emptyList.insertAfter("Z","A");
        emptyList.insertAfter("A", "Z");
        emptyList.printList();
        System.out.println("-------------");
// clearing list
        System.out.println("Clearing list (first removal should result in AZ)");
        emptyList.remove("Z");
        emptyList.printList();
        emptyList.remove("Z");
        emptyList.remove("A");
        System.out.println("-------------");
        System.out.println("Inserting before list with one element");
        emptyList.insertItemAtStart("A");
        emptyList.insertBefore("A", "Z");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Resetting list to one element");
        emptyList.remove("Z");
        System.out.println("-------------");
        System.out.println("Inserting after list with one element");
        emptyList.insertAfter("A", "Z");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Clearing list");
        emptyList.remove("Z");
        System.out.println("-------------");
        System.out.println("Removing element which does not exist, then removing element from one element list, then removing from empty list");
        emptyList.insertItemAtStart("A");
        emptyList.remove("K");
        emptyList.remove("A");
        emptyList.remove("A");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Moving things to beginning and end in empty list");
        emptyList.moveToFront("A");
        emptyList.moveToEnd("A");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Moving things to beginning and end in one element list");
        emptyList.insertItemAtStart("A");
        emptyList.moveToFront("A");
        emptyList.moveToEnd("A");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Checking head, foot pointer management");
        emptyList = new DoublyLinkedList<String>();
        emptyList.insertItemAtEnd("A");
        emptyList.remove("A");
        emptyList.insertItemAtEnd("B");
        emptyList.insertItemAtStart("C");
        emptyList.insertItemAtEnd("D");
        emptyList.printList();
        System.out.println("-------------");
        System.out.println("Checking to see which of two duplicate values is moved to front and end");
        DoublyLinkedList<String> smallList = new DoublyLinkedList<String>();
        smallList.insertItemAtEnd("A");
        smallList.insertItemAtEnd("B");
        smallList.insertItemAtEnd("D");
        smallList.insertItemAtEnd("A");
        smallList.insertItemAtEnd("C");
        smallList.moveToEnd("A");
        smallList.printList(); /*Should be B D A C A*/
        smallList.moveToFront("A");
        smallList.printList(); /*Should be A B D C A*/
    }
}
